# Generated by Django 4.0.1 on 2022-02-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetmodel',
            name='username',
        ),
    ]
